swagger: '2.0'
info:
  title: Clinical and Genomic API demo
  version: "1"
basePath: /v1
consumes:
  - application/json
produces:
  - application/json

paths:
    get:
      operationId: claims_authz_data.api.operations.get_individuals
      summary: Get all individuals
      responses:
        "200":
          description: Return individuals
          schema:
            type: array
            example: []
            items:
              $ref: '#/definitions/Individual'
        "401":
          description: Unauthenticated
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: Forbidden
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /individuals/{individual_id}:
    get:
      operationId: claims_authz_data.api.operations.get_one_individual
      summary: Get specific individual
      parameters:
        - $ref: '#/parameters/individual_id'
      responses:
        "200":
          description: Return individual
          schema:
            $ref: '#/definitions/Individual'
        "404":
          description: Individual not found
          schema:
            $ref: "#/definitions/Error"
        "401":
          description: Unauthenticated
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: Forbidden
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: Internal error
          schema:
            $ref: "#/definitions/Error"
definitions:
  Individual:
    type: object
    required:
      - description
    properties:
      id:
        type: string
        description: Participant ID
        example: "P0001"
        readOnly: true
        minLength: 1
        maxLength: 100
      status:
        type: string
        description: description of individual
        example: "Healthy"
        minLength: 1
        maxLength: 100

  Error:
    type: object
    required:
      - message
      - code
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
